### ISSUE TITLE
type ErrHelp not provided

### ISSUE THREAD

**Issue by sxwebdev** [cristalhq/flagx#5]
The documentation contains this line

```
// The return value will be ErrHelp if -help or -h were set but not defined.
```

But package does not provide type `ErrHelp`

**Comment by sxwebdev** [comment]
I figured it out. The type is returned from the standard package `flag.ErrHelp`

**Comment by cristaloleg** [comment]
Feel free to make a PR clarifying that it's from 'flag' package.

Or I will do in 1hr.
